# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-01-16T22:13:38Z"
  labels:
    app: podshortify
  name: pod_shortify
spec:
  containers:
  - args:
    - postgres
    image: docker.io/library/postgres:latest
    name: postgres
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: shortify_docker-nest-postgres-pvc
  - args:
    - redis-server
    image: docker.io/library/redis:latest
    name: redis
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /data
      name: shortify_docker-nest-redis-pvc
  - args:
    - sh
    - -c
    - npm run migration:run; npm run start:dev
    image: localhost/shortify_shortify:latest
    name: shortify
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  restartPolicy: Always
  volumes:
  - name: shortify_docker-nest-postgres-pvc
    persistentVolumeClaim:
      claimName: shortify_docker-nest-postgres
  - name: shortify_docker-nest-redis-pvc
    persistentVolumeClaim:
      claimName: shortify_docker-nest-redis
status: {}

